name: github-actions-practice
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the World
        run: echo "Hello, World!"
      - name: Greet the User
        run: echo "Hello, ${{ github.actor }}!"
